Repository itArnaudov/public, pull requests merged in 2023-12, with the labels that each got.

#5 applied final Fix code section format in readme md
  PY/test_super_mario/readme.md
Labels: good first issue

#7 work on calc #1.0
  PY/test_super_mario/calculator/calc.py
  PY/test_super_mario/calculator/readme.md
  PY/test_super_mario/test-super-mario-5/readme.md
  PY/test_super_mario/test-super-mario-5/test_super_mario-5.py
Labels: duplicate, help wanted

#8 merge fix to - scientific functions linked to issue
  PY/calculator/calc.py
  PY/calculator/readme.md
  PY/test-super-mario-5/readme.md
  PY/test-super-mario-5/test_super_mario-5.py
Labels: enhancement, help wanted

#10 M365 dev 1.0
  M365_dev/LICENSE
  M365_dev/find_time_add-in/LICENSE
  M365_dev/find_time_add-in/manifest.xml
  M365_dev/find_time_add-in/readme.md
  M365_dev/find_time_add-in/taskpane.css
  M365_dev/find_time_add-in/taskpane.html
  M365_dev/find_time_add-in/taskpane.js
Labels: bug, enhancement

#11 Chess game cpp demo
  CPP/LICENCE
  CPP/chess-game_demo.cpp
  CPP/readme.md
  M365_dev/LICENSE
  M365_dev/find_time_add-in/LICENSE
  M365_dev/find_time_add-in/manifest.xml
  M365_dev/find_time_add-in/readme.md
  M365_dev/find_time_add-in/taskpane.css
  M365_dev/find_time_add-in/taskpane.html
  M365_dev/find_time_add-in/taskpane.js
  PY/az_graph_api/LICENSE
  PY/az_graph_api/graph_api_script.py
  PY/az_graph_api/readme.md
  PY/calculator/LICENSE
  PY/test-super-mario-5/LICENSE
  azure-cli/LICENSE
  azure-powershell/LICENSE
  terraform/AWS_GCP/LICENSE
  terraform/Azure/LICENSE
Labels: enhancement

#20 Create ILB_3xVMs_back-end.tf
  terraform/Azure/ILB_3xVMs_back-end.tf
Labels: enhancement

#23 adding in aws code
  terraform/AWS_GCP/AWS-App-Load-Balancer_ILB_2xVMs_with-Vnet.tf
  terraform/AWS_GCP/GCloud-Load-Balanceing_ILB_2xVMs_with-Vnet.tf
  terraform/AWS_GCP/ILB_2xVMs_back-end_AWS.tf
  terraform/AWS_GCP/ILB_2xVMs_back-end_GCP.tf
  terraform/Azure/App Gateway in front of ILB with 2x VMs.tf
  terraform/Azure/DO-NOT-USE_Internal Load Balancer with Vnet and 2x back end hosts.tf
  terraform/Azure/ILB_3xVMs_back-end.tf
  terraform/Azure/ILB_with_Vnet.tf
  terraform/Azure/Internal Load Balancer with Vnet.tf
  terraform/Azure/Internal Load Balancer.tf
Labels: bug
